config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :transactions
  end
  resources :groups
  get 'new_user_transaction', to: 'users#new_user_transaction'
  get 'user_transactions', to: 'users#user_transactions'
  root to: 'users#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_one_attached :icon

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  validates :icon, presence: true

  belongs_to :user
  has_many :transaction_groups, dependent: :destroy
  has_many :transactions, through: :transaction_groups, source: :transfer

  scope :sorted_ASK, -> { order(name: :asc) }
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :amount, presence: true

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :transaction_groups, dependent: :destroy, foreign_key: 'transfer_id'
  has_many :groups, through: :transaction_groups

  scope :ordered_desc, -> { order(created_at: :desc) }
  scope :most_expensive_transaction, -> { where(amount: maximum(:amount)) }
  scope :most_cheapest_transaction, -> { where(amount: minimum(:amount)) }
end

app/models/transaction_group.rb
# frozen_string_literal: true

class TransactionGroup < ApplicationRecord
  belongs_to :transfer, class_name: 'Transaction'
  belongs_to :group
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }

  has_many :groups
  has_many :transactions, class_name: 'Transaction', foreign_key: 'author_id'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = Group.all.includes(:user).sorted_ASK
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.create(group_params)
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end

  def group_icon
    params.require(:group).permit(:icon)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  def index
    temp_var = current_user.transactions.includes(:groups).ordered_desc
    @transactions = temp_var
    @transactions = temp_var.select { |tr| tr.groups.empty? } unless params[:icon]

    @total_amount = @transactions.reduce(0) { |sum, cur| sum + cur.amount }
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = current_user.transactions.build(transaction_params)
    if @transaction.save
      @transaction.transaction_groups.create(show_group_id)
      redirect_to user_transaction_path(current_user, @transaction), notice: 'You successfully created a new transaction.'
    else
      render 'new'
    end
  end

  def update
    if @transaction.update(transaction_params)
      if show_group_id[:group_id]
        if @transaction.groups.empty?
          @transaction.transaction_groups.create(show_group_id)
        else
          @transaction.transaction_groups.update(show_group_id)
        end
      end
      redirect_to user_transaction_path, notice: 'Transaction updated'
    else
      render 'edit'
    end
  end

  def destroy
    if @transaction.destroy
      redirect_to user_transactions_path(icon: true), notice: 'Transaction deleted'
    else
      redirect_to root_path
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount)
  end

  def show_group_id
    params.require(:transaction).permit(:group_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show; end

  def show
    @most_expensive_transaction = current_user.transactions.most_expensive_transaction[0]
    @most_cheapest_transaction = current_user.transactions.most_cheapest_transaction[0]
  end

  def user_transactions
    @user_transactions = current_user.transactions
  end

  def new_user_transaction; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def show_user_name(current_user)
    if signed_in?
      "<li class='nav-item'>
        <div class='nav-link text-white'>
          Logged in as <strong>#{link_to current_user.name, user_path(current_user)} </strong>
        </div>
      </li>
      <li class='nav-item'>
         #{link_to 'logout', destroy_user_session_path, class: 'nav-link text-white', method: :delete}
      </li>".html_safe
    else
      "<li class='nav-item'>
        #{link_to 'Log in / Sign up', new_user_registration_path, class: 'nav-link text-white'}
      </li>".html_safe
    end
  end

  def show_transaction_icon(transaction, class_names)
    if transaction.groups.empty?
      image_tag 'empty.png', class: 'transaction_icon card-img-top mr-3 border rounded'
    else
      image_tag transaction.groups.first.icon, class: class_names
    end
  end

  def show_cheapest_and_expensivest
    unless current_user.transactions.empty?
      "<div class='mr-5 d-flex flex-column align-items-center'>
         <p class='font-weight-bold'>Expensivest</p>
         #{link_to @most_expensive_transaction.name, user_transaction_path(current_user, @most_expensive_transaction)}
      </div>
      <div class='d-flex flex-column align-items-center'>
         <p class='font-weight-bold'>Cheapest</p>
         #{link_to @most_cheapest_transaction.name, user_transaction_path(current_user, @most_cheapest_transaction)}
      </div>".html_safe
    end
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/groups/edit.html.erb
<% if !@group.errors.empty?%>
  <ul class='alert alert-danger px-5'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <% @group.errors.full_messages.each do |msg|%>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>
<p class="d-flex justify-content-center text-primary h3 font-weight-bold">Edit Group</p>
<%= form_with model: @group, url: group_path,class:'col-md-8 mx-md-auto mt-2',local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name:", class: "col-md-4 control-label" %>
    <div class="col">
      <%= f.text_field :name,autofocus: true, placeholder: 'Group name', class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class='col'>
      <%= f.label "Icon" %>
      <%= f.file_field :icon %><br>
    </div>
  </div>
  <%= f.submit "Submit", class: "btn btn-default btn-primary ml-3" %>
<% end %>

app/views/groups/index.html.erb
<section class='d-flex align-items-center flex-column mt-3'>
  <div class='w-100 bg-light rounded p-3 mb-3'>
    <%= link_to 'Create new group', new_group_path,class:'btn btn-default btn-primary' %>
  </div>
  <% @groups.each do |group| %>
    <%= link_to group_path(group),class:'w-100 transaction_link text-secondary' do %>
      <div class='w-100 bg-white rounded p-2 mb-2 border shadow d-flex'>
        <%= image_tag group.icon, class: 'transaction_icon card-img-top mr-3 border rounded' %>
        <%= group.name %>
        <p class="m-0 flex-grow-1 d-flex justify-content-end">Created by: <span class='font-italic'><%= group.user.name %></span></p>
      </div>
    <% end %>
  <% end %>
</section>

app/views/groups/new.html.erb
<% if !@group.errors.empty?%>
  <ul class='alert alert-danger px-5'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <% @group.errors.full_messages.each do |msg|%>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>
<p class="d-flex justify-content-center text-primary h3 font-weight-bold">Create Group</p>
<%= form_with scope: :group, url: groups_path,class:'col-md-8 mx-md-auto mt-2',local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name:", class: "col-md-4 control-label" %>
    <div class="col">
      <%= f.text_field :name,autofocus: true, placeholder: 'Group name', class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class='col'>
      <%= f.label 'Icon' %>
      <%= f.file_field :icon,direct_upload: true %><br>
    </div>
  </div>
  <%= f.submit "Submit", class: "btn btn-default btn-primary ml-3" %>
<% end %>

app/views/groups/show.html.erb
<section class='d-flex align-items-center flex-column mt-3'>
  <div class="transaction_card rounded mt-2" >
    <div class='d-flex justify-content-center align-items-center border-bottom border-dark pb-2 mb-1'>
      <%= image_tag @group.icon, class: 'group_icon card-img-top mr-3 border rounded rounded-circle' %>
      <span class="transaction_title card-title h4 font-italic text-secondary"><%= @group.name %></span>
    </div>
     <div class='mb-4'>
        <%= link_to edit_group_path(@group) do %>
          <button class="btn btn-secondary">
            Edit Group
          </button>
        <% end %>
      </div>

    <% @group.transactions.each do |transaction| %>
      <div class='w-100 bg-white rounded p-2 mb-2 border shadow d-flex'>
        <div class='w-100'>
          <div class='d-flex justify-content-between mb-2'>
            <span class='h4'><%= transaction.name %></span>
            <span class='font-weight-bold pr-3'>$ <%= transaction.amount %></span>
          </div>
          <p class="m-0">Created by: <span class='font-italic'><%= transaction.author.name %></span></p>
          <%= transaction.created_at.to_formatted_s(:long)  %>
        </div>
      </div>
    <% end %>

  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="py-2 bg-dark text-white d-flex justify-content-center align-items-center">
    <small>Copyright &copy; <%= link_to 'Mkrtich Sargsyan', 'https://github.com/MkrtichSargsyan',target: "_blank",class:'text-white' %></small>

</footer>

app/views/layouts/_messages.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <%= link_to root_path  do %>
      <div class='logo p-2 rounded-pill' style="background: rgb(33, 33, 34)">
        <span style='color:rgb(255, 255, 255)'>S</span>
        <span style='color:rgb(254, 251, 238)'>A</span>
        <span style='color:rgb(253, 246, 220)'>L</span>
        <span style='color:rgb(252, 242, 203)'>E</span>
        <span style='color:rgb(234, 237, 206)'>D</span>
        <span style='color:rgb(204, 233, 226)'>I</span>
        <span style='color:rgb(104, 90, 69)'>A</span>
      </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 float-right">
        <%= show_user_name(current_user) %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Transactions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class='my_container m-2'>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<p>Helooooo</p>

app/views/transactions/_list.html.erb
<% @transactions.each do |transaction| %>
    <%= link_to user_transaction_path(current_user, transaction),class:'w-100 transaction_link text-secondary' do %>
      <div class='w-100 bg-white rounded p-2 mb-2 border shadow d-flex'>
        <%= show_transaction_icon(transaction,'transaction_icon card-img-top mr-3 border rounded') %>
        <div class='w-100'>
          <div class='d-flex justify-content-between mb-2'>
            <span><%= transaction.name %></span>
            <span class='font-weight-bold pr-3'>$ <%= transaction.amount %></span>
          </div>
          <%= transaction.created_at.to_formatted_s(:long)  %>
        </div>
      </div>
    <% end %>
<% end %>

app/views/transactions/edit.html.erb
<% if !@transaction.errors.empty?%>
  <ul class='alert alert-danger px-5'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <% @transaction.errors.full_messages.each do |msg|%>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @transaction, url: user_transaction_path,class:'col-md-8 mx-md-auto mt-4',local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name:", class: "col-md-4 control-label" %>
    <div class="col">
      <%= f.text_field :name,autofocus: true, placeholder: 'Transaction name', class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, "Amount:", class: "col-md-4 control-label" %>
    <div class="col">
      <%= f.text_field :amount,autofocus: true, placeholder: 'Transaction amount', class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :group, "Select group:", class: "col-md-4 control-label" %>
    <div class="col">
      <%= f.select :group_id, Group.all.map{|group| [group.name,group.id]}, { include_blank: true },class:'input-group form-control' %>
    </div>
  </div>
  <%= f.submit "Submit", class: "btn btn-default btn-primary ml-3" %>
<% end %>

app/views/transactions/index.html.erb
<section class='d-flex align-items-center flex-column mt-3'>
  <div class='w-100 rounded p-3 mb-3' style='background: #5fb523'>
    <p class='mb-2 h5 nova_bold text-secondary'>TOTAL PAYMENTS $<%= @total_amount %> </p>
    <%= link_to 'Create new transaction', new_user_transaction_path,class:'btn btn-default btn-primary' %>
  </div>
  <%= render 'transactions/list' %>
</section>

app/views/transactions/new.html.erb
<% if !@transaction.errors.empty?%>
  <ul class='alert alert-danger px-5'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <% @transaction.errors.full_messages.each do |msg|%>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= form_with scope: :transaction, url: user_transactions_path,class:'col-md-8 mx-md-auto mt-4',local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name:", class: "col-md-4 control-label" %>
    <div class="col">
      <%= f.text_field :name,autofocus: true, placeholder: 'Transaction name', class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, "Amount:", class: "col-md-4 control-label" %>
    <div class="col">
      <%= f.text_field :amount,autofocus: true,placeholder: 'Transaction amount', class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :group, "Select group:", class: "col-md-4 control-label" %>
    <div class="col">
      <%= f.select :group_id, Group.all.map{|group| [group.name,group.id]}, { include_blank: true },class:'input-group form-control' %>
    </div>
  </div>
  <%= f.submit "Submit", class: "btn btn-default btn-primary ml-3" %>
<% end %>

app/views/transactions/show.html.erb
<section class='d-flex align-items-center flex-column mt-3'>
  <p class="text-primary h1 font-weight-bold">Details</p>
  <div class="transaction_card shadow card rounded mt-3 p-4" >
    <div class='d-flex justify-content-center align-items-center'>
    <%= show_transaction_icon(@transaction,'group_icon card-img-top mr-3') %>
      <span class="transaction_title card-title h3 font-italic text-secondary"><%= @transaction.name %></span>
    </div>
    <div class="card-body">
      <h5 class="card-title">Amount: <span class='font-italic h4'><%= @transaction.amount %> $</span></h5>
      <h5 class="card-text">Created by: <span class='font-italic h4'><%= @transaction.author.name %></span></h5>
      <p>Date: <span class='font-italic'><%= @transaction.created_at.to_formatted_s(:long)  %></span></p>
      <div>
        <%= link_to edit_user_transaction_path(@transaction) do %>
          <button class="btn btn-secondary">
            Edit
          </button>
        <% end %>
        <%= link_to user_transaction_path(@transaction), method: :delete do %>
          <button class="btn btn-danger">
            Delete
          </button>
        <% end %>
      </div>
    </div>
  </section>

app/views/users/show.html.erb
<section class='d-flex align-items-center flex-column mt-3'>
  <%= image_tag 'user.png',class:'user_icon' %>
  <h1><%= current_user.name %></h1>
  <div>
    <div class='d-flex align-items-center mb-2'>
      <%= image_tag 'transaction_icons/tr.png',class:'payment_icon rounded-circle mr-2 border p-1' %>
      <%= link_to 'All my transactions', user_transactions_path(current_user,icon:true), class:'h5 m-0 border-bottom border-dark pb-1' %>
    </div>
    <div class='d-flex align-items-center mb-2'>
      <%= image_tag 'transaction_icons/i4.jpg',class:'payment_icon rounded-circle mr-2 border p-2' %>
      <%= link_to 'All my external transactions', user_transactions_path(current_user), class:'h5 m-0 border-bottom border-dark pb-1' %>
    </div>
    <div class='d-flex align-items-center mb-2'>
      <%= image_tag 'transaction_icons/i6.webp',class:'payment_icon rounded-circle mr-2 border p-2' %>
      <%= link_to 'All groups',groups_path, class:'h5 m-0 border-bottom border-dark pb-1' %>
    </div>
  </div>

  <div class=' d-flex'>
   <%= show_cheapest_and_expensivest %>
</section>